<?php
/**
 * admin/login.php
 * Login form for the administration panel. This template emits a
 * standard HTML form and includes a CSRF hidden input generated by
 * `csrf_input_field()` from `config.php`.
 *
 * Note: the actual authentication check and session establishment
 * are performed in `admin/auth.php`.
 */

require_once 'config.php';

// If already logged in, redirect to admin panel
if (isset($_SESSION['admin_logged_in']) && $_SESSION['admin_logged_in'] === true) {
    header('Location: index.php');
    exit;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login</title>
    <?php require_once __DIR__ . '/partials/head.php'; ?>
    <link rel="stylesheet" href="/assets/css/styles.css">
    <!-- Favicons are included via admin/partials/head.php -->
    <!-- Login page styles have been moved to /assets/css/admin.css -->
</head>
<body class="admin login-page">
    <div class="login-container">
                <div class="login-header">
                        <?php
                            $cfile = __DIR__ . '/../data/content.json';
                            $c = file_exists($cfile) ? json_decode(file_get_contents($cfile), true) : [];
                            $logo = $c['images']['logo'] ?? '';
                            $logoUrl = '';
                            if ($logo) { $logoUrl = preg_match('#^https?://#i', $logo) ? $logo : '../uploads/images/'.ltrim($logo, '/'); }
                        ?>
                        <?php if ($logoUrl): ?>
                                                        <picture>
                                                            <source type="image/webp" srcset="/uploads/images/logo-48.webp 1x, /uploads/images/logo-96.webp 2x, /uploads/images/logo-192.webp 4x">
                                                            <img src="/uploads/images/logo-48.png" srcset="/uploads/images/logo-48.png 1x, /uploads/images/logo-96.png 2x, /uploads/images/logo-192.png 4x" alt="Admin" class="admin-logo">
                                                        </picture>
                        <?php else: ?>
                            <h1>🔐 Admin Login</h1>
                        <?php endif; ?>
                        <p>Website Management Panel</p>
                </div>
        
        <?php if (isset($_GET['pw_changed'])): ?>
        <div class="alert success">
            ✅ Password changed — please log in with your new password.
        </div>
        <?php endif; ?>

        <?php if (isset($_GET['timeout'])): ?>
        <div class="alert">
            ⏱️ Your session expired. Please log in again.
        </div>
        <?php endif; ?>

        <?php if (isset($_GET['error'])): ?>
        <div class="alert">
            ❌ Invalid username or password
        </div>
        <?php endif; ?>
        
        <?php if (isset($_GET['logout'])): ?>
            <div class="alert success">
            ✅ You have been logged out successfully
        </div>
        <?php endif; ?>
        
        <form action="auth.php" method="POST">
            <div class="form-group">
                <label class="form-label">Username</label>
                <input type="text" name="username" class="form-input" required autofocus>
            </div>
            
            <div class="form-group">
                <label class="form-label">Password</label>
                <input type="password" name="password" class="form-input" required>
            </div>
            
            <?php // include CSRF token inside the login form so it is submitted ?>
            <?php echo csrf_input_field(); ?>
            <button type="submit" class="btn-login">Login</button>
        </form>
        
        <p class="muted text-center mt-15 muted-footer">
            Forgot password? Contact your administrator
        </p>
    </div>
</body>
</html>
