<?php
/**
 * admin/login.php
 * Login form for the administration panel. This template emits a
 * standard HTML form and includes a CSRF hidden input generated by
 * `csrf_input_field()` from `config.php`.
 *
 * Note: the actual authentication check and session establishment
 * are performed in `admin/auth.php`.
 */

require_once 'config.php';

// If already logged in, redirect to admin panel
if (isset($_SESSION['admin_logged_in']) && $_SESSION['admin_logged_in'] === true) {
    header('Location: index.php');
    exit;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login</title>
    <?php require_once __DIR__ . '/partials/head.php'; ?>
    <!-- Favicons are included via admin/partials/head.php -->
    <!-- Login page styles have been moved to /assets/css/admin.css -->
</head>
<body class="admin login-page">
    <div class="login-container">
                <div class="login-header">
                        <?php
                            $cfile = __DIR__ . '/../data/content.json';
                            $c = file_exists($cfile) ? json_decode(file_get_contents($cfile), true) : [];
                            $logo = $c['images']['logo'] ?? '';
                            $logoUrl = '';
                            if ($logo) {
                                require_once __DIR__ . '/partials/uploads.php';
                                $logoUrl = preg_match('#^https?://#i', $logo) ? $logo : admin_image_src($logo);
                            }
                        ?>
                        <?php if ($logoUrl): ?>
                            <?php
                                // Compute responsive logo paths based on the stored image path (may be "logo/logo.png" or a URL)
                                $logoVal = $c['images']['logo'] ?? '';
                                if (preg_match('#^https?://#i', $logoVal)) {
                                    $logo48 = $logo96 = $logo192 = $logoVal;
                                    $logo48_webp = $logo96_webp = $logo192_webp = $logoVal;
                                } else {
                                    require_once __DIR__ . '/partials/uploads.php';
                                    $logo48 = admin_image_src($logoVal ? preg_replace('/\.png$/i', '-48.png', $logoVal) : 'logo-48.png');
                                    $logo96 = admin_image_src($logoVal ? preg_replace('/\.png$/i', '-96.png', $logoVal) : 'logo-96.png');
                                    $logo192 = admin_image_src($logoVal ? preg_replace('/\.png$/i', '-192.png', $logoVal) : 'logo-192.png');
                                    $logo48_webp = preg_replace('/\.png$/i', '.webp', $logo48);
                                    $logo96_webp = preg_replace('/\.png$/i', '.webp', $logo96);
                                    $logo192_webp = preg_replace('/\.png$/i', '.webp', $logo192);
                                }
                            ?>
                            <picture>
                                <source type="image/webp" srcset="<?php echo htmlspecialchars($logo48_webp); ?> 1x, <?php echo htmlspecialchars($logo96_webp); ?> 2x, <?php echo htmlspecialchars($logo192_webp); ?> 4x">
                                <img src="<?php echo htmlspecialchars($logo48); ?>" srcset="<?php echo htmlspecialchars($logo48); ?> 1x, <?php echo htmlspecialchars($logo96); ?> 2x, <?php echo htmlspecialchars($logo192); ?> 4x" alt="Admin" class="admin-logo">
                            </picture>
                        <?php else: ?>
                            <h1>🔐 Admin Login</h1>
                        <?php endif; ?>
                        <p>Website Management Panel</p>
                </div>
        
        <?php if (isset($_GET['pw_changed'])): ?>
        <div class="alert success">
            ✅ Password changed — please log in with your new password.
        </div>
        <?php endif; ?>

        <?php if (isset($_GET['timeout'])): ?>
        <div class="alert">
            ⏱️ Your session expired. Please log in again.
        </div>
        <?php endif; ?>

        <?php if (isset($_GET['error'])): ?>
        <div class="alert">
            ❌ Invalid username or password
        </div>
        <?php endif; ?>
        
        <?php if (isset($_GET['logout'])): ?>
            <div class="alert success">
            ✅ You have been logged out successfully
        </div>
        <?php endif; ?>
        
        <form action="auth.php" method="POST">
            <div class="form-group">
                <label class="form-label">Username</label>
                <input type="text" name="username" class="form-input" required autofocus>
            </div>
            
            <div class="form-group">
                <label class="form-label">Password</label>
                <input type="password" name="password" class="form-input" required>
            </div>
            
            <?php // include CSRF token inside the login form so it is submitted ?>
            <?php echo csrf_input_field(); ?>
            <button type="submit" class="btn-login">Login</button>
        </form>
        
        <p class="muted text-center mt-15 muted-footer">
            Forgot password? Contact your administrator
        </p>
    </div>
</body>
</html>

<!-- diagnostics removed -->
